### ISSUE TITLE
pom file needs to be modified

### ISSUE THREAD

**Issue by ghost** [kissaten/maven-plugin-war-example#2]
where exactly in this pom file do you add

     <configuration>
         <appName>gentle-shore-6874</appName>
     </configuration>

where gentle-shore-6874 is heroku app name ?

**Comment by Malax** [comment]
Hey there. I know this is an old issue, but just in case the information is still of value to you or someone else:

https://github.com/kissaten/maven-plugin-war-example/blob/b0543f06be27d70d3f14a8d9ea8e3028d4bcee7c/pom.xml#L29

This is the beginning of the configuration block for the maven plugin. `<appName>` goes there right next to the `<buildpacks>` setting.
